import 'app_settings.dart';
import 'models.dart';

class AppStrings {
  const AppStrings(this.language);

  final AppLanguage language;
  bool get _traditional => language == AppLanguage.traditional;

  String operator [](String key) =>
      (_traditional ? _zhHant : _zhHans)[key] ?? key;

  String algorithmName(ScrambleAlgorithm algorithm) => switch (algorithm) {
    ScrambleAlgorithm.auto => this['algorithmAuto'],
    ScrambleAlgorithm.blockShuffle => this['algorithmBlock'],
    ScrambleAlgorithm.rowShift => this['algorithmRow'],
    ScrambleAlgorithm.columnShift => this['algorithmColumn'],
    ScrambleAlgorithm.pixelPermutation => this['algorithmPixel'],
    ScrambleAlgorithm.channelDisturbance => this['algorithmChannel'],
    ScrambleAlgorithm.composite => this['algorithmComposite'],
    ScrambleAlgorithm.cherryTomato => this['algorithmTomato'],
  };

  String algorithmDescription(ScrambleAlgorithm algorithm) =>
      switch (algorithm) {
        ScrambleAlgorithm.auto => this['algorithmAutoDesc'],
        ScrambleAlgorithm.blockShuffle => this['algorithmBlockDesc'],
        ScrambleAlgorithm.rowShift => this['algorithmRowDesc'],
        ScrambleAlgorithm.columnShift => this['algorithmColumnDesc'],
        ScrambleAlgorithm.pixelPermutation => this['algorithmPixelDesc'],
        ScrambleAlgorithm.channelDisturbance => this['algorithmChannelDesc'],
        ScrambleAlgorithm.composite => this['algorithmCompositeDesc'],
        ScrambleAlgorithm.cherryTomato => this['algorithmTomatoDesc'],
      };

  static const _zhHans = <String, String>{
    'appName': 'Langbai 图片混淆',
    'appSubtitle': 'Image Scrambler',
    'offline': '完全离线',
    'workspace': '处理工作台',
    'workspaceImage': '图片混淆',
    'workspaceText': '小说 TXT',
    'settings': '设置',
    'exportHistory': '导出记录',
    'about': '关于',
    'scramble': '生成混淆图',
    'restore': '自动还原',
    'textEncode': 'Base64 转码',
    'textRestore': 'Base64 恢复',
    'scrambleShort': '混淆',
    'restoreShort': '还原',
    'heroScramble': '让画面不可直视，随时精确还原',
    'heroRestore': '自动识别算法，逐像素精确还原',
    'heroDesc': '本地处理 PNG、JPG、WebP、BMP 与 TIFF，不上传任何图片。',
    'heroTextEncode': '把小说 TXT 批量转为纯 Base64',
    'heroTextRestore': '批量恢复 Base64，原始字节完整不变',
    'heroTextDesc': '不解析小说编码，UTF-8、GBK、UTF-16 与原换行格式均按原始字节处理。',
    'importTitle': '添加图片',
    'dropTitle': '拖放图片或文件夹到这里',
    'dropDesc': '支持批量、递归子目录与原目录结构保留',
    'importTextTitle': '添加小说 TXT',
    'dropTextTitle': '拖放 TXT 或小说文件夹到这里',
    'dropTextDesc': '整文件标准 Base64 转码，批量处理并保留目录结构',
    'chooseImages': '选择图片',
    'chooseText': '选择 TXT',
    'chooseFolder': '加入文件夹',
    'configuration': '处理设置',
    'algorithm': '混淆算法',
    'chooseAlgorithm': '选择混淆算法',
    'chooseAlgorithmDesc': '查看算法特点后选择；当前选项会清晰标记。',
    'tapToChange': '点击更换',
    'selected': '已选择',
    'passwordProtection': '密码保护',
    'passwordProtectionDesc': '算法参数使用 AES-256-GCM 加密',
    'password': '输入密码',
    'manualSeed': '手动随机种子',
    'manualSeedHint': '仅在图片算法标识丢失时需要',
    'queue': '待处理图片',
    'textQueue': '待处理 TXT',
    'files': '张图片',
    'textFiles': '个 TXT',
    'folderItems': '个文件',
    'folderCompleted': '已完成',
    'emptyQueue': '还没有图片',
    'emptyQueueDesc': '选择图片、导入文件夹，或直接拖放到窗口。',
    'emptyTextQueue': '还没有 TXT 文件',
    'emptyTextQueueDesc': '选择小说 TXT、导入文件夹，或直接拖放到窗口。',
    'clear': '清空',
    'retryFailed': '重试失败项',
    'startScramble': '开始生成混淆图',
    'startRestore': '开始自动还原',
    'startTextEncode': '开始 Base64 转码',
    'startTextRestore': '开始 Base64 恢复',
    'cancel': '处理完当前图片后停止',
    'cancelAction': '取消',
    'processing': '正在处理',
    'queued': '等待中',
    'completed': '已完成',
    'failed': '失败',
    'ready': '准备就绪',
    'selectFirst': '请先添加图片或文件夹',
    'allCompleted': '全部处理完成',
    'partialCompleted': '处理完成，部分图片失败',
    'exportCancelled': '已取消选择导出位置',
    'updateAvailable': '发现新版本',
    'downloadUpdate': '查看并下载',
    'dismiss': '稍后',
    'currentVersion': '当前版本',
    'language': '界面语言',
    'simplifiedChinese': '简体中文',
    'traditionalChinese': '繁體中文',
    'appearance': '外观',
    'systemTheme': '跟随系统',
    'lightTheme': '浅色',
    'darkTheme': '深色',
    'exportSettings': '导出设置',
    'askEveryTime': '每次询问导出位置',
    'askEveryTimeDesc': '关闭后自动导出到固定文件夹',
    'defaultExport': '固定导出文件夹',
    'notSelected': '尚未选择',
    'choose': '选择',
    'historySettings': '撤回记录',
    'historyRetention': '记录自动清理时间',
    'historyRetentionDesc': '到期只清理记录，不删除已导出的文件',
    'retention1': '1 天',
    'retention7': '7 天（默认）',
    'retention30': '30 天',
    'retention90': '90 天',
    'retentionForever': '永久保留',
    'performance': '批量性能',
    'concurrency': '同时处理数量',
    'concurrencyDesc': '多张图片并发混淆；大型图片占用内存更多',
    'concurrencyAuto': '自动（最多 4 张）',
    'concurrency1': '1 张',
    'concurrency2': '2 张',
    'concurrency4': '4 张',
    'concurrency8': '8 张',
    'concurrencyNow': '当前并发',
    'historyTitle': '导出与撤回记录',
    'historySubtitle': '只记录本软件生成的输出，可撤回任意未清理批次。',
    'historyEmpty': '还没有导出记录',
    'historyEmptyDesc': '成功导出图片或 TXT 后会显示在这里。',
    'undo': '撤回导出',
    'undoing': '正在撤回',
    'undone': '已撤回',
    'undoConfirmTitle': '撤回这次导出？',
    'undoConfirmDesc': '将删除仍与导出时完全一致的文件；已修改文件会保留。',
    'undoDeleted': '已删除',
    'undoModified': '已修改并跳过',
    'undoMissing': '已不存在',
    'undoFailed': '处理失败',
    'historyImageScramble': '图片混淆',
    'historyImageRestore': '图片还原',
    'historyTextEncode': 'TXT 转码',
    'historyTextRestore': 'TXT 恢复',
    'updates': '更新',
    'checkUpdates': '自动检查 GitHub Releases',
    'checkNow': '立即检查',
    'privacyTitle': '隐私与数据',
    'privacyDesc': '所有图片与密码仅在本机处理；应用不包含服务器、账号系统或统计组件。',
    'close': '完成',
    'compatibility': '兼容算法',
    'passwordUnsupported': '小番茄兼容模式为确定性算法，不支持密码参数。',
    'algorithmAuto': '自动识别（推荐）',
    'algorithmBlock': '网格块打乱',
    'algorithmRow': '行循环位移',
    'algorithmColumn': '列循环位移',
    'algorithmPixel': '像素级伪随机置换',
    'algorithmChannel': 'RGB 通道扰动',
    'algorithmComposite': '复合混淆',
    'algorithmTomato': '小番茄图片混淆',
    'algorithmAutoDesc': '读取 Langbai 标识；识别不到时可手动选择。',
    'algorithmBlockDesc': '以随机大小网格重新排列画面区域。',
    'algorithmRowDesc': '对每一行应用独立的循环偏移。',
    'algorithmColumnDesc': '对每一列应用独立的循环偏移。',
    'algorithmPixelDesc': '使用可逆映射重新排列全部像素。',
    'algorithmChannelDesc': '置换并扰动 RGB 通道，保留透明度。',
    'algorithmCompositeDesc': '组合分块、行位移与通道扰动，混淆强度最高。',
    'algorithmTomatoDesc': 'Gilbert 广义 Hilbert 曲线＋黄金比例偏移，与参考工具双向兼容。',
    'pixelExact': '像素无损',
    'pngOutput': '统一输出 PNG',
    'folderPreserved': '保留目录结构',
    'noUpdate': '当前已是最新版本',
    'updateCheckFailed': '检查更新失败，请稍后重试',
    'folderEmpty': '文件夹中没有受支持的图片',
    'textFolderEmpty': '文件夹中没有 TXT 文件',
    'invalidPassword': '请输入密码后再开始处理',
    'invalidSeed': '请输入有效的非负整数随机种子',
    'base64Standard': '标准 Base64',
    'byteExact': '字节无损',
  };

  static const _zhHant = <String, String>{
    'appName': 'Langbai 圖片混淆',
    'appSubtitle': 'Image Scrambler',
    'offline': '完全離線',
    'workspace': '處理工作台',
    'workspaceImage': '圖片混淆',
    'workspaceText': '小說 TXT',
    'settings': '設定',
    'exportHistory': '匯出記錄',
    'about': '關於',
    'scramble': '生成混淆圖',
    'restore': '自動還原',
    'textEncode': 'Base64 轉碼',
    'textRestore': 'Base64 恢復',
    'scrambleShort': '混淆',
    'restoreShort': '還原',
    'heroScramble': '讓畫面不可直視，隨時精確還原',
    'heroRestore': '自動識別演算法，逐像素精確還原',
    'heroDesc': '本機處理 PNG、JPG、WebP、BMP 與 TIFF，不上傳任何圖片。',
    'heroTextEncode': '把小說 TXT 批次轉為純 Base64',
    'heroTextRestore': '批次恢復 Base64，原始位元組完整不變',
    'heroTextDesc': '不解析小說編碼，UTF-8、GBK、UTF-16 與原換行格式均按原始位元組處理。',
    'importTitle': '加入圖片',
    'dropTitle': '拖放圖片或資料夾到這裡',
    'dropDesc': '支援批次、遞迴子目錄與保留原目錄結構',
    'importTextTitle': '加入小說 TXT',
    'dropTextTitle': '拖放 TXT 或小說資料夾到這裡',
    'dropTextDesc': '整個檔案使用標準 Base64 轉碼，批次處理並保留目錄結構',
    'chooseImages': '選擇圖片',
    'chooseText': '選擇 TXT',
    'chooseFolder': '加入資料夾',
    'configuration': '處理設定',
    'algorithm': '混淆演算法',
    'chooseAlgorithm': '選擇混淆演算法',
    'chooseAlgorithmDesc': '查看演算法特點後選擇；目前選項會清楚標記。',
    'tapToChange': '點擊更換',
    'selected': '已選擇',
    'passwordProtection': '密碼保護',
    'passwordProtectionDesc': '演算法參數使用 AES-256-GCM 加密',
    'password': '輸入密碼',
    'manualSeed': '手動隨機種子',
    'manualSeedHint': '僅在圖片演算法標識遺失時需要',
    'queue': '待處理圖片',
    'textQueue': '待處理 TXT',
    'files': '張圖片',
    'textFiles': '個 TXT',
    'folderItems': '個檔案',
    'folderCompleted': '已完成',
    'emptyQueue': '還沒有圖片',
    'emptyQueueDesc': '選擇圖片、匯入資料夾，或直接拖放到視窗。',
    'emptyTextQueue': '還沒有 TXT 檔案',
    'emptyTextQueueDesc': '選擇小說 TXT、匯入資料夾，或直接拖放到視窗。',
    'clear': '清空',
    'retryFailed': '重試失敗項目',
    'startScramble': '開始生成混淆圖',
    'startRestore': '開始自動還原',
    'startTextEncode': '開始 Base64 轉碼',
    'startTextRestore': '開始 Base64 恢復',
    'cancel': '處理完目前圖片後停止',
    'cancelAction': '取消',
    'processing': '正在處理',
    'queued': '等待中',
    'completed': '已完成',
    'failed': '失敗',
    'ready': '準備就緒',
    'selectFirst': '請先加入圖片或資料夾',
    'allCompleted': '全部處理完成',
    'partialCompleted': '處理完成，部分圖片失敗',
    'exportCancelled': '已取消選擇匯出位置',
    'updateAvailable': '發現新版本',
    'downloadUpdate': '查看並下載',
    'dismiss': '稍後',
    'currentVersion': '目前版本',
    'language': '介面語言',
    'simplifiedChinese': '简体中文',
    'traditionalChinese': '繁體中文',
    'appearance': '外觀',
    'systemTheme': '跟隨系統',
    'lightTheme': '淺色',
    'darkTheme': '深色',
    'exportSettings': '匯出設定',
    'askEveryTime': '每次詢問匯出位置',
    'askEveryTimeDesc': '關閉後自動匯出到固定資料夾',
    'defaultExport': '固定匯出資料夾',
    'notSelected': '尚未選擇',
    'choose': '選擇',
    'historySettings': '撤回記錄',
    'historyRetention': '記錄自動清理時間',
    'historyRetentionDesc': '到期只清理記錄，不刪除已匯出的檔案',
    'retention1': '1 天',
    'retention7': '7 天（預設）',
    'retention30': '30 天',
    'retention90': '90 天',
    'retentionForever': '永久保留',
    'performance': '批次效能',
    'concurrency': '同時處理數量',
    'concurrencyDesc': '多張圖片並行混淆；大型圖片會占用更多記憶體',
    'concurrencyAuto': '自動（最多 4 張）',
    'concurrency1': '1 張',
    'concurrency2': '2 張',
    'concurrency4': '4 張',
    'concurrency8': '8 張',
    'concurrencyNow': '目前並行',
    'historyTitle': '匯出與撤回記錄',
    'historySubtitle': '只記錄本軟體生成的輸出，可撤回任意未清理批次。',
    'historyEmpty': '還沒有匯出記錄',
    'historyEmptyDesc': '成功匯出圖片或 TXT 後會顯示在這裡。',
    'undo': '撤回匯出',
    'undoing': '正在撤回',
    'undone': '已撤回',
    'undoConfirmTitle': '撤回這次匯出？',
    'undoConfirmDesc': '將刪除仍與匯出時完全一致的檔案；已修改檔案會保留。',
    'undoDeleted': '已刪除',
    'undoModified': '已修改並略過',
    'undoMissing': '已不存在',
    'undoFailed': '處理失敗',
    'historyImageScramble': '圖片混淆',
    'historyImageRestore': '圖片還原',
    'historyTextEncode': 'TXT 轉碼',
    'historyTextRestore': 'TXT 恢復',
    'updates': '更新',
    'checkUpdates': '自動檢查 GitHub Releases',
    'checkNow': '立即檢查',
    'privacyTitle': '隱私與資料',
    'privacyDesc': '所有圖片與密碼僅在本機處理；應用程式不包含伺服器、帳號系統或統計元件。',
    'close': '完成',
    'compatibility': '相容演算法',
    'passwordUnsupported': '小番茄相容模式為確定性演算法，不支援密碼參數。',
    'algorithmAuto': '自動識別（建議）',
    'algorithmBlock': '網格塊打亂',
    'algorithmRow': '列循環位移',
    'algorithmColumn': '欄循環位移',
    'algorithmPixel': '像素級偽隨機置換',
    'algorithmChannel': 'RGB 通道擾動',
    'algorithmComposite': '複合混淆',
    'algorithmTomato': '小番茄圖片混淆',
    'algorithmAutoDesc': '讀取 Langbai 標識；識別不到時可手動選擇。',
    'algorithmBlockDesc': '以隨機大小網格重新排列畫面區域。',
    'algorithmRowDesc': '對每一列套用獨立的循環偏移。',
    'algorithmColumnDesc': '對每一欄套用獨立的循環偏移。',
    'algorithmPixelDesc': '使用可逆映射重新排列全部像素。',
    'algorithmChannelDesc': '置換並擾動 RGB 通道，保留透明度。',
    'algorithmCompositeDesc': '組合分塊、列位移與通道擾動，混淆強度最高。',
    'algorithmTomatoDesc': 'Gilbert 廣義 Hilbert 曲線＋黃金比例偏移，與參考工具雙向相容。',
    'pixelExact': '像素無損',
    'pngOutput': '統一輸出 PNG',
    'folderPreserved': '保留目錄結構',
    'noUpdate': '目前已是最新版本',
    'updateCheckFailed': '檢查更新失敗，請稍後再試',
    'folderEmpty': '資料夾中沒有支援的圖片',
    'textFolderEmpty': '資料夾中沒有 TXT 檔案',
    'invalidPassword': '請輸入密碼後再開始處理',
    'invalidSeed': '請輸入有效的非負整數隨機種子',
    'base64Standard': '標準 Base64',
    'byteExact': '位元組無損',
  };
}
